### ISSUE TITLE
Все сцены не должны лежать в одной папке

### ISSUE THREAD

**Issue by Trubkin** [gdsmithrus/Multirun#2]
В идеале, код, имея ссылку на сцену, должен узнать от нее, в какой папке она лежит.
Иначе скан всей директории проекта вручную.

**Comment by gdsmithrus** [comment]
Решено, файлы со сценами не привязаны к директории

**Comment by Trubkin** [comment]
1. Создать две разные сцены-болванки.
2. Поместить их в разные директории
3. Добавить их в проект (желательно с возможностью попасть на эти сцены)
4. Сбилдить с помощью плагина 
5. Убедиться, что проблема не решена

**Comment by Trubkin** [comment]
Прочти название тикета внимательно.

**Comment by gdsmithrus** [comment]
Посмотри код внимательно еще раз

**Comment by Trubkin** [comment]
Действительно, все в порядке
